### ISSUE TITLE
Éviter dépôt dans dépôt

### ISSUE THREAD

**Issue by oliviercailloux** [Dauphine-MIDO/plaquette-MIDO#4]
Il faut créer le deuxième dépôt comme un autre répertoire de base (`../dépôt`), pas comme un sous-répertoire du répertoire de plaquette-MIDO.

**Comment by barnabegeffroy** [comment]
Je n'ai pas encore réussi, une erreur s'est produite au moment de pousser. Je continue de chercher !

**Comment by barnabegeffroy** [comment]
Avec ça, c'est mieux!
