### ISSUE TITLE
Doc déploiement

### ISSUE THREAD

**Issue by oliviercailloux** [Dauphine-MIDO/plaquette-MIDO#5]
Il nous faut une doc brève (dans le README de ce projet par exemple) qui indique ce qu’il faut faire pour activer la génération du PDF et son dépôt (créer un token d’accès à un autre dépôt dans lequel le PDF et le log sera déposé ; indiquer les variables d’environnement adéquates à Travis…)

**Comment by barnabegeffroy** [comment]
J'ai compléter la doc pour expliquer le cas où seul les logs sont poussés

**Comment by oliviercailloux** [comment]
Super.
