### ISSUE TITLE
Faire échouer le build Travis

### ISSUE THREAD

**Issue by oliviercailloux** [Dauphine-MIDO/plaquette-MIDO#7]
Je ne suis pas convaincu que le build Travis échoue actuellement si le programme crashe avec une exception. Il faudrait aussi vérifier que le PDF existe, pas seulement que Maven arrive à lancer le programme.

À ce propos, certains messages pourraient être plus précis. Par exemple "Document generation succeeded." probablement devrait être "Program started successfully.", si, comme je soupçonne, le fait que Maven arrive à démarrer le programme n’implique pas que la génération du document ait fonctionné.

**Comment by barnabegeffroy** [comment]
Avec tes deux derniers commits, le problème est réglé ? Je ne suis pas sûr d'avoir bien compris.
` if mvn exec:java "-Dexec.mainClass=io.github.oliviercailloux.plaquette_mido_soap.M1ApprBuilder"` ne suffit pas à s'assurer de la génération des documents ?
Si cela ne suffit pas on peut changer la valeur du `BUILT_EXIT_CODE` au moment où l'on vérifie que le pdf est bien présent (`if test -f "${FILE_PDF}"; then`) au lien de le faire lors de l’exécution du programme M1ApprBuilder

**Comment by oliviercailloux** [comment]
Je ne sais pas. Essaie de modifier le code temporairement de façon à ce qu’il crashe, par exemple en ajoutant un verify(false) qq part.

**Comment by barnabegeffroy** [comment]
J'ai jeté une exception à la fin du main, le code a crashé. Le pdf est généré mais le build Travis a bien échoué. Le `if mvn exec:java "-Dexec.mainClass=io.github.oliviercailloux.plaquette_mido_soap.M1ApprBuilder"` ne teste pas seulement le lancement du programme mais sa réussite. 

Pour l'instant : 
- si le pdf existe, celui-ci est poussé dans le dépôt d'arrivée même si le code a crashé 
- le build Travis échoue

Est-ce notre finalité ? Ou souhaite-on qu'à partir du moment où le pdf existe, le build Travis n'échoue pas ? Ou bien si le code crashe, le pdf ne soit pas poussé même s'il est généré ?

**Comment by oliviercailloux** [comment]
Ok, je doutais que Maven détecte que le code crashe. Je me demande comment ça fonctionne. Peux-tu trouver une documentation officielle concernant le comportement (en terme de code d’erreur ou autre) de mvn exec:java ? Et l’indiquer en commentaire dans le script.

Le comportement actuel du script est parfait, cette question était la seule zone d’ombre.

**Comment by barnabegeffroy** [comment]
J'avais plutôt l'impression que c'était le script bash qui détectait l'erreur ou non... Je vais me renseigner.

**Comment by barnabegeffroy** [comment]
Voici la [documentation](https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Conditional-Constructs) que j'ai lue.

**Comment by oliviercailloux** [comment]
Cette partie est claire. Ma question implicite était : dans quels cas exactement mvn exec:java renvoie-t-il un code non nul ?

**Comment by barnabegeffroy** [comment]
Est-ce que [cela](https://www.mojohaus.org/exec-maven-plugin/usage.html#Java_goal) répond à ta question ?

**Comment by oliviercailloux** [comment]
Non, mais laissons tomber ma question, c’était plutôt de la curiosité.
